<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/1/12
 * Time: 15:10
 */

namespace Admin\Controller;
use Admin\Service\CompayService;

class CompayController extends  AuthController
{
    private  static $CompayService;

    public  function  _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        self::$CompayService=new CompayService();
    }
    //区域 公司
    public  function  setFitment_h(){
        $result=self::$CompayService->setFitment_h();
//        $a=$result['data']['result'];
//        $result['data']=array();
//        $result['data']['result']=$a;
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //等级 公司
    public  function  setFitment_d(){
        $result=self::$CompayService->setFitment_d();
//        $a=$result['data']['result'];
//        $result['data']=array();
//        $result['data']['result']=$a;
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //服务 公司
    public  function  setFitment_f(){
        $result=self::$CompayService->setFitment_f();
//        $a=$result['data']['result'];
//        $result['data']=array();
//        $result['data']['result']=$a;
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //规模 公司
    public  function  setFitment_g(){
        $result=self::$CompayService->setFitment_g();
//        $a=$result['data']['result'];
//        $result['data']=array();
//        $result['data']['result']=$a;
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //默认 公司
    public  function  setFitment_m(){
        $result=self::$CompayService->setFitment_m();
//        $a=$result['data']['result'];
//        $result['data']=array();
//        $result['data']['result']=$a;
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    /**
     * 找装修公司
     *link是新加字端是链接的意思
     *thumb是图片路径
     * name是名字
     *信誉指数scores
     * 公司地址addr
     * 联系电话show_phone
     * 服务次数yuyue_num
      案例设计case_num
      签单次数tenders_num
     */
    public  function   setFitment(){
        //等级4是普通5是砖石
        $groupid=I('groupid');
        //服务
        $attr_value_f=I('attr_value_f');
        //规模
        $attr_value_m=I('attr_value_m');
        //区域
        $area_name = I('area_name');
        //默认等等
        $tenders_num= I('tenders_num');
//        $closed = 0;
//        $audit = 1;
        //等级4是普通5是砖石
//        $groupid= "普通装修公司";
        //服务
//        $attr_value_f="家装";
        //规模
//        $attr_value_m="500万元以上";
        //区域
//        $area_name = '环翠区';
        $closed = 0;
        $audit = 1;
//        $tenders_num='口碑';
        $pageNumber=I('pageNumber',1, 'intval');// 当前页，首页为1
        $pageSize = I('pageSize', 10, 'intval');// 分页用 每页数量
        $result=self::$CompayService->setFitment($groupid,$attr_value_f,$attr_value_m,$area_name,$closed,$audit,$tenders_num,$pageNumber,$pageSize);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    /**
     * 找装修公司详情
     */
    public  function  cy_compay_a(){
        $company_id=I('company_id');
        $result=self::$CompayService->cy_compay_a($company_id);
        $this->loger('result', $result);
       // $this->ajaxReturn($result);
    }
    /**
     * 设计师详情设计案例
     */
    public  function  cy_compay_h(){
        $company_id=I('company_id');
        $result=self::$CompayService->cy_compay_h($company_id);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    /**
     * 找装修公司，设计团队
     */
    public  function  cy_compay_c(){
        $company_id=I('company_id');
        $result=self::$CompayService->cy_compay_c($company_id);
        $this->loger('result', $result);
    }
    /**
     * 找装修公司，评论显示
     */
    public  function  cy_compay_f(){
        $company_id=I('company_id');
        $pageNumber=I('pageNumber',1, 'intval');// 当前页，首页为1
        $pageSize = I('pageSize', 10, 'intval');// 分页用 每页数量
        $result=self::$CompayService->cy_compay_f($company_id,$pageNumber,$pageSize);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    /**
     * 找装修公司，插入评论
     */
    public  function  cy_compay_k(){
        //评论内容
        $content=I('content');
        $compay_id=I('compay_id');
        $score1=I('score1');
        $score2=I('score2');
        $score3=I('score3');
        $score4=I('score4');
        $score5=I('score5');
        $city_id="7";
        $result=self::$CompayService->cy_compay_k($city_id,$compay_id,$score1,$score2,$score3,$score4,$score5,$content);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //免费预约
    public  function cy_compay_yuyue(){
        $company_id=I('company_id');
        //电话
        $mobile=I('mobile');
        //姓名
        $contact=I('contact');
        $city_id = 7;
        $status=0;
        $dateline=time();
        $clientip=gethostbyname($_ENV['COMPUTERNAME']);
        $result=self::$DesignerService->cy_compay_yuyue($company_id,$city_id,$mobile,$contact,$status,$dateline,$clientip);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //免费预约查询
    public  function cy_compay_yuyuecx(){
        $company_id=I('company_id');
        $result=self::$DesignerService->cy_compay_yuyuecx($company_id);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
}