<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/1/12
 * Time: 15:47
 */

namespace Admin\Controller;


use Admin\Service\DesignerService;
class DesignerController extends  AuthController
{
    private  static $DesignerService;

    public  function  _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        self::$DesignerService=new DesignerService();
    }
    /**
     *  找设计师
     *link是新加字端是链接的意思
     *face是图片路径
     * name是名字
     *case_num套
     * 毕业院校school
     * 联系电话mobile
     *设计理念slogan
     */
    public  function  Designer(){
        //等级
        $groupid=I('groupid');
        //经验
        $attr_value_f=I('attr_value_f');
        //职位
        $attr_value_m=I('attr_value_m');
        //区域
        $area_name = I('area_name');
//        $area_name = '高区';

        //默认等等
        $tenders_num= I('tenders_num');
        $closed = 0;
        $audit = 1;
//        //等级
//        $groupid='普通设计师';
//        //经验
//        $attr_value_f="1-3年";
//        //职位
//        $attr_value_m="见习设计师";
//        $area_name = '环翠区';
//        $closed = 0;
//        $audit = 1;
//        $tenders_num='默认';
        $pageNumber=I('pageNumber',1, 'intval');// 当前页，首页为1
        $pageSize = I('pageSize', 10, 'intval');// 分页用 每页数量
        $result=self::$DesignerService->Designer($groupid,$attr_value_f,$attr_value_m,$area_name,$closed,$audit,$tenders_num,$pageNumber,$pageSize);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //免费预约
    public  function cy_designer_yuyue(){
        $uid=I('designer_id');
        //电话
        $mobile=I('mobile');
        //姓名
        $contact=I('contact');
        $city_id = 7;
        $status=0;
        $dateline=time();
        $clientip=gethostbyname($_ENV['COMPUTERNAME']);
        $result=self::$DesignerService->cy_designer_yuyue($uid,$city_id,$mobile,$contact,$status,$dateline,$clientip);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //免费预约查询
    public  function cy_designer_yuyuecx(){
        $uid=I('uid');
        $result=self::$DesignerService->cy_designer_yuyuecx($uid);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //区域 设计师
    public  function  Designer_h(){
        $result=self::$DesignerService->Designer_h();
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //等级 设计师
    public  function  Designer_d(){
        $result=self::$DesignerService->Designer_d();
        $a=$result['data']['result'];
        $result['data']=array();
        $result['data']['result']=$a;
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //经验 设计师
    public  function  Designer_j(){
        $result=self::$DesignerService->Designer_j();
        $a=$result['data']['result'];
        $result['data']=array();
        $result['data']['result']=$a;
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //职位 设计师
    public  function  Designer_z(){
        $result=self::$DesignerService->Designer_z();
        $a=$result['data']['result'];
        $result['data']=array();
        $result['data']['result']=$a;
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //默认 设计师
    public  function  Designer_m(){
        $result=self::$DesignerService->Designer_m();
        $a=$result['data']['result'];
        $result['data']=array();
        $result['data']['result']=$a;
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    /**
     * 设计师详情
     */
    public  function  cy_Designer_a(){
        $uid=I('uid');
//      $uid='119';
        $result=self::$DesignerService->cy_Designer_a($uid);
        $this->loger('result', $result);
       // $this->ajaxReturn($result);
    }
    /**
     * 设计师，评论显示
     */
    public  function  cy_Designer_f(){
         $uid=I('uid');
//        $uid='119';
        $pageNumber=I('pageNumber',1, 'intval');// 当前页，首页为1
        $pageSize = I('pageSize', 10, 'intval');// 分页用 每页数量
        $result=self::$DesignerService->cy_Designer_f($uid,$pageNumber,$pageSize);
        $this->loger('result', $result);
//        $this->ajaxReturn($result);
    }
    /**
     * 设计师公司，插入评论
     */
    public  function  cy_Designer_k(){
         $uid=I('uid');
//        $uid='119';
        //评论内容
        $content=I('content');
        $designer_id=$uid;
        $score1=I('score1');
        $score2=I('score2');
        $score3=I('score3');
        $city_id="7";
        $result=self::$DesignerService->cy_Designer_k($city_id,$designer_id,$score1,$score2,$score3,$content);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    /**
     * 设计师公司，他的文章
     *
     */
    public  function  cy_Designer_article(){
        $uid=I('uid');
        $pageNumber=I('pageNumber',1, 'intval');// 当前页，首页为1
        $pageSize = I('pageSize', 10, 'intval');// 分页用 每页数量
        $result=self::$DesignerService->cy_Designer_article($uid,$pageNumber,$pageSize);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    /**
     * 设计师公司，他的文章内容
     *
     */
    public  function  cy_Designer_showinfo(){
        $uid=I('article_id');
        $result=self::$DesignerService->cy_Designer_showinfo($uid);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    /**
     * 设计师公司，他的文章相关文章
     */
    public  function  cy_Designer_showinfoa(){
        $uid=I('uid');
        $result=self::$DesignerService->cy_Designer_showinfoa($uid);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    /**
     * 设计师收藏
     */
    public  function  cy_Designer_attention_num(){
        $uid=I('uid');
        $result=self::$DesignerService->cy_Designer_attention_num($uid);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
}