<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/1/17
 * Time: 10:42
 */

namespace Admin\Controller;
use Admin\Service\DiaryService;

class DiaryController extends  AuthController
{
    private  static $DiaryService;
    public  function  _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        self::$DiaryService=new DiaryService();
    }
    //学装修-装修日记装修
    public  function  Diary(){
        $pageNumber=I('pageNumber',1, 'intval');// 当前页，首页为1
        $pageSize=I('pageSize',10, 'intval');// 当前页，首页为1
        $result=self::$DiaryService->Diary($pageNumber,$pageSize);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //学装修-装修日记户型
    public  function  Diary_aa(){
        $pageNumber=I('pageNumber',1, 'intval');// 当前页，首页为1
        $pageSize=I('pageSize',10, 'intval');// 当前页，首页为1
        $result=self::$DiaryService->Diary_aa($pageNumber,$pageSize);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //学装修-装修日记阶段
    public  function  Diary_bb(){
        $pageNumber=I('pageNumber',1, 'intval');// 当前页，首页为1
        $pageSize=I('pageSize',10, 'intval');// 当前页，首页为1
        $result=self::$DiaryService->Diary_bb($pageNumber,$pageSize);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //学装修-装修日记_详细页面
    public  function  Diary_a(){
        $diary_id=I('diary_id');
//        $diary_id='5';
        $result=self::$DiaryService->Diary_a($diary_id);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //学装修-装修日记_文章
    //这个没有用
    public  function  Diary_b(){
//        $diary_id=I('diary_id');
        $diary_id='4';
        $result=self::$DiaryService->Diary_b($diary_id);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    /**
     *学装修-装修日记_评论
     */
    public  function  Diary_c(){
        $diary_id=I('diary_id');
        $pageNumber=I('pageNumber',1, 'intval');// 当前页，首页为1
        $pageSize=I('pageSize',10, 'intval');// 当前页，首页为1
        $result=self::$DiaryService->Diary_c($diary_id,$pageNumber,$pageSize);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    /**
     * 学装修-装修日记_评论插入
     */
    public  function  Diary_d(){
        $diary_id=I('diary_id');
        $content=I('content');
        $result=self::$DiaryService->Diary_d($diary_id,$content);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //户型
    public  function  Diary_h(){
        $result=self::$DiaryService->Diary_h();
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //装修
    public  function  Diary_z(){
        $result=self::$CaseeService->Diary_z();
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //阶段
    public  function  Diary_j(){
        $result=self::$DiaryService->Diary_j();
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
}