<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/1/4
 * Time: 14:41
 */

namespace Admin\Controller;

use Admin\Service\FilterService;
class FilterController extends AuthController
{
    private  static $FilterService;

    public  function  _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        self::$FilterService=new FilterService();
    }

    //区域 设计师
    public  function  Designer_h(){
        $result=self::$FilterService->Designer_h();
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //等级 设计师
    public  function  Designer_d(){
        $result=self::$FilterService->Designer_d();
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //经验 设计师
    public  function  Designer_j(){
        $result=self::$FilterService->Designer_j();
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //职位 设计师
    public  function  Designer_z(){
        $result=self::$FilterService->Designer_z();
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //默认 设计师
    public  function  Designer_m(){
        $result=self::$FilterService->Designer_m();
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //区域 工人
    public  function  Mechanic_h(){
        $result=self::$FilterService->Mechanic_h();
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //等级 工人
    public  function  Mechanic_d(){
        $result=self::$FilterService->Mechanic_d();
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //工种 工人
    public  function  Mechanic_g(){
        $result=self::$FilterService->Mechanic_g();
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //默认 工人
    public  function  Mechanic_m(){
        $result=self::$FilterService->Mechanic_m();
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }

}