<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/9/29
 * Time: 9:43
 */

namespace Admin\Controller;


use Admin\Service\GsService;

class gsController extends  AuthController
{
   private  static $GsService;

   public  function  _initialize()
   {
       parent::_initialize(); // TODO: Change the autogenerated stub
       self::$GsService=new GsService();
   }
   //一级找家装公司
   public  function  setcompany(){
       $pageNumber=I('pageNumber',1, 'intval');// 当前页，首页为1
       $pageSize=I('pageSize',10, 'intval');// 当前页，首页为1
       $result=self::$GsService->setcompany($pageNumber,$pageSize);
       $this->loger('result', $result);
       $this->ajaxReturn($result);
   }
    //首页轮播图
   public  function  setgs(){
       $result=self::$GsService->setgs();
       $this->loger('result', $result);
       $this->ajaxReturn($result);
   }
    //热门分类
   public  function  sethot(){
       $result=self::$GsService->sethot();
       $this->loger('result', $result);
       $this->ajaxReturn($result);
   }
   //热搜
   public  function  cy_tophot(){
       $result=self::$GsService->cy_tophot();
       $this->loger('result', $result);
       $this->ajaxReturn($result);
   }
  //历史热搜
    public  function  cy_history(){
        $result=self::$GsService->cy_history();
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //热搜插入
    public  function  sethot_a(){
        $name=I('name');
        $result=self::$GsService->sethot_a($name);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //搜索
    public  function  cy_historyss(){
//        $name='威海';
//        $cate='1';
        $name=I('name');
        $cate=I('cate');
        $pageNumber=I('pageNumber',1, 'intval');// 当前页，首页为1
        $pageSize=I('pageSize',10, 'intval');// 当前页，首页为1
        $result=self::$GsService->cy_historyss($name,$cate,$pageNumber,$pageSize);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    /**
     *  找工人
     *link是新加字端是链接的意思
     */
    public  function  Mechanic(){
//        //等级
//        $groupid='普通技工';
//        //工种
//        $attr_value_f="木工";
//        $area_name = '环翠区';
        //等级
        $groupid=I('groupid');
        //工种
        $attr_value_f=I('attr_value_f');
        //区域
        $area_name =I('area_name');
        //默认等等
        $tenders_num= I('tenders_num');;
        $closed = 0;
        $audit = 1;
//        $tenders_num='默认';
        $pageNumber=I('pageNumber',1, 'intval');// 当前页，首页为1
        $pageSize = I('pagesize', 10, 'intval');// 分页用 每页数量
        $result=self::$GsService->Mechanic($groupid,$attr_value_f,$area_name,$closed,$audit,$tenders_num,$pageNumber,$pageSize);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    /**
     * 头部图片
     * thumb是图片路径
     */
   public  function  AdvItem(){
    // $advid = I("advid");
       $advid = 1;
       $result=self::$GsService->AdvItem($advid);
       $this->loger('result', $result);
       $this->ajaxReturn($result);
   }
    /**
     * 热门案例图片链接
     * link是图片链接
     * thumb图片路径
     */
    public  function  BlockItem(){
        // $block_id = I("block_id");
        $blockid = 5;
        $result=self::$GsService->BlockItem($blockid);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }

}
