<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/2/9
 * Time: 10:08
 */

namespace Admin\Controller;
use Admin\Service\ShopService;

class ShopController extends AuthController
{
    private  static $ShopService;

    public  function  _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        self::$ShopService=new ShopService();
    }
    //家居商城-分类一级分类
    public  function  cy_shop_cate(){
        $result=self::$ShopService->cy_shop_cate();
        $this->loger('result', $result);
    }
    //家居商城-分类二级分类
    public  function  cy_shop_cateb(){
        $id=I('id');
        $result=self::$ShopService->cy_shop_cateb($id);
        $this->loger('result', $result);
    }
    //家居商城-首页轮播图
    public  function  cy_shop_photosy(){
        $result=self::$ShopService->cy_shop_photosy();
        $this->loger('result', $result);
    }

    //家居商城-商城默认，价格，销量
    public  function  cy_shop_s(){
        $result=self::$ShopService->cy_shop_s();
        $this->loger('result', $result);
    }
    //家居商城-商城首页商品列表
    public  function  cy_shop_syxq(){
        $mr=I('mr');
        $xl=I('xl');
        $jg=I('jg');
        $cat_id=I('cat_id');
        $pageNumber=I('pageNumber',1, 'intval');// 当前页，首页为1
        $pageSize=I('pageSize',10, 'intval');// 当前页，首页为1
        $result=self::$ShopService->cy_shop_syxq($mr,$xl,$jg,$cat_id,$pageNumber,$pageSize);
        $this->loger('result', $result);
    }
    //家居商城-商品详细页
    public  function  cy_shop_xq(){
        $product_id=I('product_id');
        $result=self::$ShopService->cy_shop_xq($product_id);
        $this->loger('result', $result);
    }
    //家居商城-商品咨询
    public  function  cy_shop_spzx(){
        //姓名
        $name=I('name');
        //电话
        $phone=I('phone');
        //地址
        $address=I('address');
        $shop_id=I('shop_id');
        $product_id=I('product_id');
                //姓名
//        $name='666';
//        //电话
//        $phone='18363100063';
//        //地址
//        $address='旱的';
//        $shop_id=8;
//        $product_id=7;
        $result=self::$ShopService->cy_shop_spzx($name,$phone,$address,$shop_id,$product_id);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }


    //家居商城-首页商家列表选择
    public  function  cy_shop_splb(){
        $result=self::$ShopService->cy_shop_splb();
        $this->loger('result', $result);
    }
    //家居商城-商家列表
    public  function  cy_shop_lb(){
        $cat_id=I('cat_id');
        $pageNumber=I('pageNumber',1, 'intval');// 当前页，首页为1
        $pageSize=I('pageSize',10, 'intval');// 当前页，首页为1
        $result=self::$ShopService->cy_shop_lb($cat_id,$pageNumber,$pageSize);
        $this->loger('result', $result);
    }
    //家居商城-商家详情
    public  function  cy_shop_sjxq(){
        $shop_id=I('shop_id');
        $result=self::$ShopService->cy_shop_sjxq($shop_id);
        $this->loger('result', $result);
    }
    //家居商城-商家全部商品
    public  function  cy_shop_sjqb(){
        $shop_id=I('shop_id');
        $pageNumber=I('pageNumber',1, 'intval');// 当前页，首页为1
        $pageSize=I('pageSize',10, 'intval');// 当前页，首页为1
        $result=self::$ShopService->cy_shop_sjqb($shop_id,$pageNumber,$pageSize);
        $this->loger('result', $result);
    }
    //家居商城-商家关注店铺
    public  function  cy_shop_spgz(){
        $shop_id=I('shop_id');
        $result=self::$ShopService->cy_shop_spgz($shop_id);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //家居商城-商家商品分类
    public  function  cy_shop_spfl(){
        $shop_id=I('shop_id');
        $result=self::$ShopService->cy_shop_spfl($shop_id);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //家居商城-店铺简介
    public  function  cy_shop_spjj(){
        $shop_id=I('shop_id');
        $result=self::$ShopService->cy_shop_spjj($shop_id);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //家居商城-加入购物车
    public  function  cy_shop_gwc(){
        $product_id=I('product_id');
        $result=self::$ShopService->cy_shop_gwc($product_id);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //家居商城-加入购物车加一件
    public  function  cy_shop_gwcj(){
        $product_id=I('product_id');
        $result=self::$ShopService->cy_shop_gwcj($product_id);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //家居商城-加入购物车删除
    public  function  cy_shop_up(){
        $product_id=I('product_id');
        $result=self::$ShopService->cy_shop_up($product_id);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
    //商城首页-我的购物车-订单信息
    public  function  cy_shop_ddxx(){
        $shop_id=I('shop_id');
        //地址
        $addr=I('addr');
        //电话
        $mobile=I('mobile');
        //备注
        $note=I('note');
        //商品数量
        $product_count=I('product_count');
        //商品种类
        $product_number=I('product_number');
        //商品金额
        $product_amount=I('product_amount');
        //收货人
        $contact=I('contact');
        $result=self::$ShopService->cy_shop_ddxx($shop_id,$addr,$mobile,$note,$product_count,$product_number,$product_amount,$contact);
        $this->loger('result', $result);
        $this->ajaxReturn($result);
    }
}